CREATE TABLE IF NOT EXISTS SENSOR_READINGS (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    sensor_id VARCHAR2(50) NOT NULL,
    reading_type VARCHAR2(50) NOT NULL,
    value NUMBER NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    location VARCHAR2(100),
    status VARCHAR2(20) DEFAULT 'ACTIVE'
); 