-- Create table with Oracle syntax (if not exists)
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists 
  FROM user_tables 
  WHERE table_name = 'SENSOR_READINGS';
  
  IF table_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE SENSOR_READINGS (
      ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      PARCELA_ID VARCHAR2(20) NOT NULL,
      HUMEDAD NUMBER NOT NULL,
      NITROGENO NUMBER NOT NULL,
      PH NUMBER NOT NULL,
      FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )';
  END IF;
END;
/ 