-- Drop table if exists (H2 syntax)
DROP TABLE IF EXISTS SENSOR_READINGS;

-- Create table with H2 syntax
CREATE TABLE SENSOR_READINGS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PARCELA_ID VARCHAR(20) NOT NULL,
    HUMEDAD DECIMAL NOT NULL,
    NITROGENO DECIMAL NOT NULL,
    PH DECIMAL NOT NULL,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
); 